#cloud-config
datasource:
  Ec2:
    strict_id: false
ssh_pwauth: no
users:
- name: windler47
  sudo: 'ALL=(ALL) NOPASSWD:ALL'
  shell: /bin/bash
  ssh_authorized_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMB1NLxM7VWE5oCKFFHsXMuFihHHU4QII/8hUkklmuEw"
# write_files:
#   - path: "/usr/local/etc/tf-install.sh"
#     permissions: "755"
#     content: |
#       #!/bin/bash

#       # Install WireGuard
#       sudo apt update
#       sudo apt install -y wireguard

#       # Generate wireguard key
#       sudo wg genkey | tee privatekey | wg pubkey > publickey


#       # Install Terraform
#       echo "Installing Terraform"
#       sudo curl -sSL https://hashicorp-releases.yandexcloud.net/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip -o /usr/local/etc/terraform.zip
#       sudo unzip /usr/local/etc/terraform.zip -d /usr/local/etc/
#       sudo install -o root -g root -m 0755 /usr/local/etc/terraform /usr/local/bin/terraform
#       sudo rm -rf /usr/local/etc/terraform /usr/local/etc/terraform.zip /usr/local/etc/LICENSE.txt
#     defer: true
# runcmd:
#   - [sudo, bash, "/usr/local/etc/tf-install.sh"]